
export const LANGS = ["RU", "UZ", "EN"];
 
export const T = {
  RU: {
    // Nav
    home: "🏠 Главная",
    order: "🛒 Заказ",
    contact: "📞 Контакты",
    // Home
    subtitle: "Топлёный Курдюк",
    whyTitle: "Почему DumbaGold?",
    orderBtn: "Заказать сейчас →",
    features: [
      { icon: "✨", title: "Без запаха", desc: "Очищен по премиум технологии" },
      { icon: "🤍", title: "Белоснежный", desc: "Чисто белый натуральный цвет" },
      { icon: "💧", title: "Без осадков", desc: "100% чистый курдючный жир" },
      { icon: "🐑", title: "Натуральный", desc: "Курдюк от отборных баранов" },
    ],
    badges: ["✨ Без запаха", "🤍 Белоснежный", "💧 Без осадков"],
    // Order
    chooseSize: "Выберите объём",
    yourOrder: "🛒 Ваш заказ",
    total: "Итого",
    sum: "Сумма",
    placeOrder: "Оформить заказ",
    orderTitle: "Оформление заказа",
    orderSub: "Введите данные для связи",
    nameLabel: "Ваше имя",
    namePlaceholder: "Например: Алишер",
    phoneLabel: "Номер телефона",
    phonePlaceholder: "+998 90 123 45 67",
    confirmBtn: "Подтвердить заказ →",
    successTitle: "Заказ отправлен!",
    successSub: "Мы свяжемся с вами в ближайшее время",
    errName: "Введите ваше имя",
    errPhone: "Введите номер телефона",
    errSend: "Ошибка отправки. Попробуйте ещё раз.",
    orderLabel: "📦 Ваш заказ",
    jar: "Банка",
    pcs: "шт.",
    products: [
      { id: 1, weight: "200 г", price: 60000, desc: "Идеально для пробы", popular: false },
      { id: 2, weight: "400 г", price: 120000, desc: "Популярный выбор", popular: true },
    ],
    popularTag: "⭐ Популярный",
    chooseQty: "Выберите количество",
    currency: "сум",
    // Contact
    contactSub: "Заказы и вопросы — пишите напрямую",
    tgBtn: "Написать в Telegram",
    waBtn: "Написать в WhatsApp",
    workHours: "Режим работы",
    delivery: "Доставка",
    deliveryText: "По всему Ташкенту — быстро и аккуратно",
    about: "О продукте",
    aboutText: "DumbaGold — 100% натуральный топлёный курдючный жир. Без запаха, белоснежного цвета, без осадков. Банки 200 г и 400 г.",
    address: "Адрес",
    addressText: "Ташкент, Юнусабадский район",
    monSat: "Пн — Сб",
    sun: "Воскресенье",
    mapTitle: "Мы на карте",
  },
  UZ: {
    home: "🏠 Bosh sahifa",
    order: "🛒 Buyurtma",
    contact: "📞 Aloqa",
    subtitle: "Eritilgan Dumba Yog'i",
    whyTitle: "Nima uchun DumbaGold?",
    orderBtn: "Hozir buyurtma →",
    features: [
      { icon: "✨", title: "Hidsiz", desc: "Premium texnologiya bilan tozalangan" },
      { icon: "🤍", title: "Oppoq", desc: "Toza oq tabiiy rang" },
      { icon: "💧", title: "Cho'kmasiz", desc: "100% toza dumba yog'i" },
      { icon: "🐑", title: "Tabiiy", desc: "Tanlangan qo'ylardan dumba" },
    ],
    badges: ["✨ Hidsiz", "🤍 Oppoq", "💧 Cho'kmasiz"],
    chooseSize: "Hajmni tanlang",
    yourOrder: "🛒 Buyurtmangiz",
    total: "Jami",
    sum: "Summa",
    placeOrder: "Buyurtma berish",
    orderTitle: "Buyurtmani rasmiylashtirish",
    orderSub: "Aloqa ma'lumotlarini kiriting",
    nameLabel: "Ismingiz",
    namePlaceholder: "Masalan: Alisher",
    phoneLabel: "Telefon raqam",
    phonePlaceholder: "+998 90 123 45 67",
    confirmBtn: "Buyurtmani tasdiqlash →",
    successTitle: "Buyurtma yuborildi!",
    successSub: "Tez orada siz bilan bog'lanamiz",
    errName: "Ismingizni kiriting",
    errPhone: "Telefon raqamini kiriting",
    errSend: "Yuborishda xatolik. Qaytadan urinib ko'ring.",
    orderLabel: "📦 Buyurtmangiz",
    jar: "Bank",
    pcs: "dona",
    products: [
      { id: 1, weight: "200 g", price: 60000, desc: "Sinab ko'rish uchun ideal", popular: false },
      { id: 2, weight: "400 g", price: 120000, desc: "Mashhur tanlov", popular: true },
    ],
    popularTag: "⭐ Mashhur",
    chooseQty: "Miqdorni tanlang",
    currency: "so'm",
    contactSub: "Buyurtma va savollar — to'g'ridan-to'g'ri yozing",
    tgBtn: "Telegramda yozish",
    waBtn: "WhatsAppda yozish",
    workHours: "Ish vaqti",
    delivery: "Yetkazib berish",
    deliveryText: "Butun Toshkent bo'ylab — tez va ehtiyotkorlik bilan",
    about: "Mahsulot haqida",
    aboutText: "DumbaGold — 100% tabiiy eritilgan dumba yog'i. Hidsiz, oppoq rangli, cho'kmasiz. 200 g va 400 g bankalar.",
    address: "Manzil",
    addressText: "Toshkent, Yunusobod tumani",
    monSat: "Du — Sha",
    sun: "Yakshanba",
    mapTitle: "Xaritada biz",
  },
  EN: {
    home: "🏠 Home",
    order: "🛒 Order",
    contact: "📞 Contact",
    subtitle: "Rendered Lamb Fat",
    whyTitle: "Why DumbaGold?",
    orderBtn: "Order Now →",
    features: [
      { icon: "✨", title: "Odorless", desc: "Purified with premium technology" },
      { icon: "🤍", title: "Snow White", desc: "Pure white natural color" },
      { icon: "💧", title: "No Sediment", desc: "100% pure lamb tail fat" },
      { icon: "🐑", title: "Natural", desc: "From carefully selected sheep" },
    ],
    badges: ["✨ Odorless", "🤍 Snow White", "💧 No Sediment"],
    chooseSize: "Choose size",
    yourOrder: "🛒 Your order",
    total: "Total",
    sum: "Amount",
    placeOrder: "Place Order",
    orderTitle: "Place your order",
    orderSub: "Enter your contact details",
    nameLabel: "Your name",
    namePlaceholder: "E.g.: Alisher",
    phoneLabel: "Phone number",
    phonePlaceholder: "+998 90 123 45 67",
    confirmBtn: "Confirm order →",
    successTitle: "Order sent!",
    successSub: "We will contact you shortly",
    errName: "Enter your name",
    errPhone: "Enter your phone number",
    errSend: "Send error. Please try again.",
    orderLabel: "📦 Your order",
    jar: "Jar",
    pcs: "pcs",
    products: [
      { id: 1, weight: "200 g", price: 60000, desc: "Perfect for trying", popular: false },
      { id: 2, weight: "400 g", price: 120000, desc: "Popular choice", popular: true },
    ],
    popularTag: "⭐ Popular",
    chooseQty: "Choose quantity",
    currency: "sum",
    contactSub: "Orders & questions — write directly",
    tgBtn: "Message on Telegram",
    waBtn: "Message on WhatsApp",
    workHours: "Working hours",
    delivery: "Delivery",
    deliveryText: "All over Tashkent — fast and careful",
    about: "About the product",
    aboutText: "DumbaGold — 100% natural rendered lamb tail fat. Odorless, snow-white, no sediment. Jars of 200 g and 400 g.",
    address: "Address",
    addressText: "Tashkent, Yunusabad district",
    monSat: "Mon — Sat",
    sun: "Sunday",
    mapTitle: "Find us on the map",
  },
};